export {TeacherDashboard} from "./TeacherDashboard";
export {SeperateSubjectDetails} from "./SeperateSubjectDetails";
export {TeacherAddNewCourse} from "./TeacherAddNewCourse";
export {TeacherSavedVideo} from "./TeacherSavedVideo";
export {TeacherSavedMaterial} from "./TeacherSavedMaterial";
export {TeacherAssignment} from "./TeacherAssignment";
export {TeacherExam} from "./TeacherExam";
export {ParticularAssignmentView} from "./ParticularAssignmentView";
export {ParticularExamView} from "./ParticularExamView";